// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC39dZp5fyaodhYNwdyKgUnY0hSvmzBiaw',
    appId: '1:363562232546:web:57da37add136caf8050cbb',
    messagingSenderId: '363562232546',
    projectId: 'debatedais-20b7f',
    authDomain: 'debatedais-20b7f.firebaseapp.com',
    storageBucket: 'debatedais-20b7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUABv1O2xzVX1_YK3SdFVDPyCpewIKjwA',
    appId: '1:363562232546:android:da4cb0b31faf0f0d050cbb',
    messagingSenderId: '363562232546',
    projectId: 'debatedais-20b7f',
    storageBucket: 'debatedais-20b7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBede1xSRPW68ShEtEFm_hKk6EGGUEj-Fg',
    appId: '1:363562232546:ios:7de9869b2eaf5b67050cbb',
    messagingSenderId: '363562232546',
    projectId: 'debatedais-20b7f',
    storageBucket: 'debatedais-20b7f.appspot.com',
    iosBundleId: 'com.debatedais.debatedais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBede1xSRPW68ShEtEFm_hKk6EGGUEj-Fg',
    appId: '1:363562232546:ios:7de9869b2eaf5b67050cbb',
    messagingSenderId: '363562232546',
    projectId: 'debatedais-20b7f',
    storageBucket: 'debatedais-20b7f.appspot.com',
    iosBundleId: 'com.debatedais.debatedais',
  );
}
